schema_version: 1

context:
  version: "7.7.0"

package:
  name: mongomock-ng
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mongomock-ng/mongomock_ng-${{ version }}.tar.gz
  sha256: ac30cb0768689a6777ae8f2979cff27a0a9d4a3ec44d8be66efac6deed3e07eb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - packaging
    - pytz
    - sentinels
    - pandas

tests:
  - python:
      imports:
        - mongomock_ng
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Replacement fake pymongo stub for testing simple MongoDB-dependent code
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/engFelipeMonteiro/mongomock-ng

extra:
  recipe-maintainers:
    - jan-janssen
